server:
  log_level: info

metrics:
  wal_directory: /etc/agent/data
  global:
    remote_write:
        - url: http://mimir:8080/api/v1/push
          headers:
            X-Scope-OrgID: "default-mimir"

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true