# Do not use this configuration in production.
# It is for demonstration purposes only.
# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter

# Configure Mimir to use Minio as object storage backend.
common:
  storage:
    backend: s3
    s3:
      endpoint: minio-mimir:9000
      access_key_id: minio
      secret_access_key: 55237114-df30-42f8-a3e3-4f67bcb901f2
      insecure: true
      bucket_name: mimir

ingester:
  ring:
    replication_factor: 1

# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

# Use memberlist, a gossip-based protocol, to enable the 3 Mimir replicas to communicate
memberlist:
  gossip_nodes: 1
  join_members: [mimir]

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://localhost:8080/alertmanager
  ring:
    # Quickly detect unhealthy rulers to speed up the tutorial.
    heartbeat_period: 2s
    heartbeat_timeout: 10s

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /etc/mimir-alertmanager.yaml
  external_url: http://localhost:8080/alertmanager
  sharding_ring:
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

server:
  log_level: info